# Generated by Django 3.1.3 on 2020-11-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('was_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='answer_file',
            field=models.FileField(default=None, upload_to='answers/'),
            preserve_default=False,
        ),
    ]
