# Generated by Django 3.1.3 on 2020-11-05 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('was_rest', '0002_score_answer_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='answer_file',
            new_name='file',
        ),
    ]
