# Generated by Django 3.1.3 on 2020-11-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('was_rest', '0004_auto_20201105_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
